### ISSUE TITLE
test_translator.sh: no output in file ```correct```

### ISSUE THREAD

**Issue by josephwinston** [agrippa/spark-swat#2]
I'm attempting to finish up the changes for OS X.  I'm using java 1.8.0_66, scala 2.10, hadoop 2.6.3, and spark 1.6.  After running `test_translator` in the directory `swat`.  The file `correct` is empty while `generated`` has:

```
#pragma OPENCL EXTENSION cl_khr_fp64 : enable

static __global void *alloc(__global void *heap, volatile __global uint *free_index, unsigned int heap_size, int nbytes, int *alloc_failed) {
   __global unsigned char *cheap = (__global unsigned char *)heap;
   uint rounded = nbytes + (8 - (nbytes % 8));
   uint offset = atomic_add(free_index, rounded);
   if (offset + nbytes > heap_size) { *alloc_failed = 1; return 0x0; }
   else return (__global void *)(cheap + offset);
}
typedef struct __attribute__ ((packed)) org_apache_spark_rdd_cl_tests_PrimitiveInputPrimitiveOutputTest$_s org_apache_spark_rdd_cl_tests_PrimitiveInputPrimitiveOutputTest$;

struct __attribute__ ((packed)) org_apache_spark_rdd_cl_tests_PrimitiveInputPrimitiveOutputTest$_s{

};

typedef struct This_s{
   } This;
static int org_apache_spark_rdd_cl_tests_PrimitiveInputPrimitiveOutputTest$$anon$1__apply$mcII$sp(This *this, int in){

   return((in + 3));
}
static int org_apache_spark_rdd_cl_tests_PrimitiveInputPrimitiveOutputTest$$anon$1__apply(This *this, int in){

   return(org_apache_spark_rdd_cl_tests_PrimitiveInputPrimitiveOutputTest$$anon$1__apply$mcII$sp(this, in));
}
__kernel void run(
      __global int* restrict in0,
      __global int* restrict out, int N, int iter) {
   This thisStruct;
   This* this=&thisStruct;
   for (int i = get_global_id(0); i < N; i += get_global_size(0)) {
      out[i] = org_apache_spark_rdd_cl_tests_PrimitiveInputPrimitiveOutputTest$$anon$1__apply(this, in0[i]);

   }
}
```

Before I start digging through the test code, any suggestions on why the `correct` file is empty?

**Comment by agrippa** [comment]
Thanks for the comment Jody, this was an issue of me not providing enough documentation of the code generation testing framework. I've just added additional documentation in the README at:

https://github.com/agrippa/spark-swat/blob/master/swat/README.md

Could you see if that clears up the issue?

**Comment by josephwinston** [comment]
Close the issue. The only note is that test_translator.sh should be run in the swat dir so that the dynamic libraries are in the current directory.

**Comment by josephwinston** [comment]
swat sh test_translator.sh
PrimitiveInputPrimitiveOutputTest$ PASSED
PrimitiveInputObjectOutputTest$ PASSED
ObjectInputObjectOutputTest$ PASSED
ReferenceExternalArrayTest$ PASSED
ReferenceExternalObjectArrayTest$ PASSED
ReferenceExternalScalarTest$ PASSED
ExternalFunctionTest$ PASSED
Tuple2InputTest$ PASSED
Tuple2ObjectInputTest$ PASSED
Tuple2ObjectInputDirectTest$ PASSED
Tuple2InputPassToFuncTest$ PASSED
Tuple2ObjectInputPassToFuncTest$ PASSED
Tuple2ObjectInputPassDirectlyToFuncTest$ PASSED
Tuple2OutputTest$ PASSED
Tuple2ObjectOutputTest$ PASSED
Tuple2InputOutputTest$ PASSED
KMeansTest$ PASSED
DenseVectorInputTest$ PASSED
SparseVectorInputTest$ PASSED
SparseVectorAssignTest$ PASSED
ArrayAllocTest$ PASSED
DenseVectorOutputTest$ PASSED
SparseVectorOutputTest$ PASSED
PrimitiveArrayBroadcastTest$ PASSED
DenseVectorBroadcastTest$ PASSED
SparseVectorBroadcastTest$ PASSED
Tuple2DenseInputTest$ PASSED
ClassExternalFunctionTest$ PASSED
Tuple2DenseOutputTest$ PASSED
Tuple2BroadcastTest$ PASSED
Tuple2ObjectBroadcastTest$ PASSED
PrimitiveArrayInputTest$ PASSED
ArrayOutputTest$ PASSED
ByteArrayInputTest$ PASSED
ExtensionTest$ PASSED
AsyncMapTest$ PASSED
AsyncPrimitiveArrayInputTest$ PASSED
AsyncArrayOutputTest$ PASSED
AsyncByteArrayInputTest$ PASSED
